---
title: "KDE"
author: "Shaine"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    number_sections: true
    toc: true
    toc_float:
      collapsed: false
      toc_depth: 5
    fig_caption: true
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.align = "center", fig.width = 5, fig.height = 3, comment="", warning = FALSE, message = FALSE)
```

# The dataset

The following could be used as simulation settings for the thetas

Generate mean values from N(23.8, sd), where sd = 3.6, sd = 6, sd = 2

K = 5, 10, 30, 51

```{r}
library(dplyr)
library(kableExtra)
library(doParallel)
library(foreach)
library(tictoc)


sd <- 3.6 #  sd = 3.6, sd = 6, sd = 2
mean <- 23.8

set.seed(123974)
theta <- rnorm(51, mean, sd)
df <- readRDS("../../data/mean_travel_time_ranking_2011.rds")
df$theta_k <- theta
full_dataset <- df %>% select(theta_k, k,S)
kable(full_dataset) %>% kable_styling(bootstrap_options = "responsive")
```

SE can be the same one used in the study of Klein 

```{r results='asis'}
alpha <- 0.1
K <- 10
B<- 1000
dataset <- full_dataset[order(full_dataset$k),][1:K,]
kable(dataset) %>% kable_styling(bootstrap_options = "responsive")
```

# Algorithm 1: Stepwise Implementation

## Step 1

(a)

```{r results='asis'}
set.seed(123974)
thetahat_star <- foreach(i = 1:K, .combine = cbind) %do% {
  foreach(b = 1:B, .combine = c) %do% {
    rnorm(1, mean = dataset[i, 'theta_k'], sd = dataset[i, 'S'])}}

colnames(thetahat_star) <- paste0("thetahat_star", 
                                  sprintf("%02d", 1:K))

kable(head(thetahat_star)) %>% kable_styling(bootstrap_options = "responsive")
```


```{r results='asis'}
set.seed(123974)
sorted_thetahat_star <- t(apply(thetahat_star, 1, sort))
colnames(sorted_thetahat_star) <- paste0("sorted_thetahat_star", 
                                         sprintf("%02d", 1:K))
kable(head(sorted_thetahat_star)) %>% kable_styling(bootstrap_options = "responsive")
```




(b)

```{r}
variance_vector <- dataset$S^2
variance_vector
```


```{r results='asis'}
# for b = 1
# if k = 1
k<-10
b<-1
minuend <- thetahat_star^2 + rep(variance_vector, each = nrow(thetahat_star))
#sqrt(among[b,k]^2 - sorted_thetahat_star[b, ][k]^2)
kable(head(minuend)) %>% kable_styling(bootstrap_options = "responsive")
```

```{r results='asis'}
sigma_hat_star <- sqrt(t(apply(minuend, 1, sort)) - sorted_thetahat_star^2)
kable(head(sigma_hat_star)) %>% kable_styling(bootstrap_options = "responsive")
```

(c)


```{r}
sorted_theta_hat <- sort(dataset$theta_k)

t_star <- apply(abs((sorted_thetahat_star - rep(sorted_theta_hat, each = nrow(sorted_thetahat_star)))/sigma_hat_star), 1, max)
t_star[1:6]
```

## Step 2

```{r}
t_hat <- quantile(t_star, probs = 1 - alpha)
t_hat
```

## Step 3

```{r}
theta_hat <- dataset$theta_k

sigma_hat <- sqrt(sort(theta_hat^2 + variance_vector) - sorted_theta_hat^2)
sigma_hat
```

## Resulting CI

```{r}
sorted_theta_hat - t_hat*sigma_hat
```

```{r}
sorted_theta_hat + t_hat*sigma_hat
```


# Algorithm 1: Full Implementation

```{r results='asis'}
source("../../R/algo1_parametric.R")

res <- run_algorithm1(B, dataset, seed = 123974, alpha = 0.1)

kable(res) %>% kable_styling(bootstrap_options = "responsive")
```

# Algorithm 2


```{r eval = FALSE}
source("../../R/algo1_parametric.R")
get_coverage <- function(dataset_or, 
                         K, 
                         reps = 5, # step 4
                         B=100, 
                         alpha= 0.10){
  foreach(iter = 1:reps, 
          .combine = rbind,
          .packages = c("foreach", "arrow", "dplyr"),
          .export = c("run_algorithm1","get_ranks", 
                      "get_t2")
          ) %dopar% {
  dataset <- dataset_or
  
  # step 1 =====================================================================
  set.seed(iter)
  
  # sir mike's theta.h
  theta_hat <- foreach(i = 1:K, .combine = cbind) %do% {
    rnorm(1, mean = dataset[i, 'theta_k'],  sd = dataset[i, 'S'])}
  
  sort_reference <- data.frame(theta = dataset$theta_k,
                               theta_hat = t(theta_hat))
  
  dataset$theta_k <- NULL
  # for the dataset, replace the means with theta.h, matching S
  dataset$theta_k <- t(theta_hat)

  # step 2 =====================================================================
  result <- run_algorithm1(B, dataset, iter, alpha)
  
  # step 3 =====================================================================
  #sorted_indices <- result$sorted_indices
  sorted_theta <- sort(dataset_or$theta_k)#sort_reference$theta[sorted_indices]
  sorted_thetahat <- sort(sort_reference$theta_hat)


  inside_check_2 <- sum((sorted_theta > result$ci_lower) &
                        (sorted_theta < result$ci_upper))


  tuple_list <- t(apply(result[,c('ci_lower', 'ci_upper')], 1, function(row) as.numeric(row)))
  ind_rank_range_length <- sapply(1:K, function(x) length(get_ranks(x, tuple_list)$ranks))
  t2_val <- get_t2(ind_rank_range_length)

  #write_feather(tab_result, sprintf("../output/iters/test/K%d/sorted_ci_%04d.feather", K, iter))

  data.frame(t2 = t2_val,
             inside_check_2 = inside_check_2)
}
}

```


```{r eval = FALSE}
#sd <- 3.6 #  sd = 3.6, sd = 6, sd = 2
mean <- 23.8

df <- readRDS("../../data/mean_travel_time_ranking_2011.rds")

cl=parallel::makeCluster(15)
registerDoParallel(cl)

sds <- c(2, 3.6, 6)
Ks <- c(51, 40, 30, 20, 10)

for (sd in sds) {
  set.seed(123974)
  theta <- rnorm(51, mean, sd)
  df$theta_k <- theta
  full_dataset <- df %>% select(theta_k, k,S)

  for (K in Ks) {
    dataset <- full_dataset[order(full_dataset$k),][1:K,]
    #dataset_or <- df[order(df$theta_k), ][seq(1,50,5), ] #df[order(df$theta_k), ][1:K, ]
    dataset_or <- dataset
    true_theta <- sort(dataset_or$theta_k)
    
    
    tic("Running...")
    coverage_output_df <- get_coverage(dataset_or, 
                                       K, 
                                       reps = 1000, 
                                       B=500, 
                                       alpha=0.10)
    toc()
  
    saveRDS(coverage_output_df,  paste0("output/coverage_probability_",K,"_", sd, ".rds"))
    coverage_output_df
    }
}

stopCluster(cl)
```


```{r results='asis'}
sds <- c(2, 3.6, 6)
Ks <- c(51, 40, 30, 20, 10)

param_grid <- expand.grid(K = Ks, sd = sds)

results <- do.call(rbind, lapply(seq_len(nrow(param_grid)), function(i) {
  K <- param_grid$K[i]
  sd <- param_grid$sd[i]
  
  a <- readRDS(paste0("output/coverage_probability_", K, "_", sd, ".rds"))
  
  data.frame(
    K = K,
    sd = sd,
    Coverage = mean(a$inside_check_2 == K),
    Within_CI_mean = mean(a$inside_check_2),
    Within_CI_max = max(a$inside_check_2),
    Within_CI_min = min(a$inside_check_2),
    T_mean = mean(a$t2)
  )
}))


kable(results %>% arrange(-K, -sd) %>% select(K, sd, Coverage, T_mean)) %>% kable_styling(bootstrap_options = "responsive")
```









