---
title: "Code Checking"
output: html_notebook
---

```{r}
df <- readRDS("data/mean_travel_time_ranking_2011.rds")
mean <- 23.8
sd <- 3.6 #2 #3.6 #c(2, 3.6, 6)
K <- c(10)#(51, 40, 30, 20, 10, 5)
corr <- c(0.5)#,0.5,0.9)
alpha <- c(0.05)#c(0.05, 0.1, 0.15, 0.2)
B <- 600

set.seed(123974)
true_theta <- rnorm(K, mean, sd)
true_sds <- df$S[1:K]
    
true_theta
```

```{r}
block_corr <- function(block_sizes, rho_within, rho_between) {
  B <- length(block_sizes)
  N <- sum(block_sizes)

  if (length(rho_within) == 1) {
    rho_within <- rep(rho_within, B)
  }

  Sigma <- matrix(rho_between, nrow = N, ncol = N)
  diag(Sigma) <- 1

  idx <- 1
  for (b in seq_len(B)) {
    block_idx <- idx:(idx + block_sizes[b] - 1)
    Sigma[block_idx, block_idx] <- rho_within[b]
    diag(Sigma[block_idx, block_idx]) <- 1
    idx <- idx + block_sizes[b]
  }

  return(Sigma)
}

block1 <- block_corr(block_sizes=c(4,6), rho_within=c(0.85, 0.25), rho_between=0.0)
block1
```


```{r}
0.3*(c(10,20,30,40,50))
```

```{r}
0.3*(c(10,20,30,40,50))
0.7*(c(10,20,30,40,50))
```

```{r}
block_unb
```



```{r}
block1 <- block_corr(block_sizes=c(4,6), rho_within=c(0.85, 0.25), rho_between=0.0)
block1 <- block_corr(block_sizes=c(8,12), rho_within=c(0.85, 0.25), rho_between=0.0)
block1 <- block_corr(block_sizes=c(15,15), rho_within=c(0.85, 0.25), rho_between=0.0)
block1 <- block_corr(block_sizes=c(20,20), rho_within=c(0.85, 0.25), rho_between=0.0)
block1 <- block_corr(block_sizes=c(25,25), rho_within=c(0.85, 0.25), rho_between=0.0)
block <- block_corr(block_sizes=c(25,25), rho_within=c(0.9, 0.1), rho_between=0.0) # B2
# block_corr(block_sizes=c(K/2,K/2), rho_within=c(0.9, 0.1), rho_between=0.0)
# block_corr(block_sizes=c(.3*K,.7*K), rho_within=c(0.9, 0.1), rho_between=0.0)

K <- 10
block_unb <- block_corr(block_sizes=c(.2*K,.3*K, .5*K), rho_within=c(0.9, 0.5, 0.1), rho_between=0.0)
tol = 1e-8
eval <- eigen(block_unb)$values
all(eval >= -abs(tol * max(eval)))
block_unb
```


```{r}
# corr_matrix <- (1 - corr) * diag(K) + corr * matrix(1, K, K)
# variance_vector <- true_sds^2
# delta <- diag(variance_vector)
# varcovar_matrix <- delta^(1/2) %*% corr_matrix %*% delta^(1/2)
# varcovar_matrix
```

```{r}
# variance_vector <- diag(varcovar_matrix)
# sqrt(variance_vector) ==  true_sds
```








```{r}
# source("R/compute_metrics.R")
# stopImplicitCluster()
# library(doRNG)
# registerDoSEQ()
# 
# df <- readRDS("data/mean_travel_time_ranking_2011.rds")
# mean <- 23.8
# sds <- c(2, 3.6, 6)
# K <- c(10)#(51, 40, 30, 20, 10, 5)
# corr <- c(0.1,0.5)
# 
# for (sd in sds) {
#   for (r in corr) {
#   print(cat("RESULTS FOR SD",sd, 'CORRELATION', r))
#   corr_matrix <- (1 - r) * diag(K) + r * matrix(1, K, K)
# 
#   set.seed(123974)
#   true_theta <- rnorm(K, mean, sd)
#   print(true_theta)
#   print(true_sds)
#   true_sds <- df$S[1:K]
#   variance_vector <- true_sds^2
#   delta <- diag(variance_vector)
#   varcovar_matrix <- delta^(1/2) %*% corr_matrix %*% delta^(1/2)
#   out <- implement_algorithm2(
#       true_theta = true_theta,
#       K = K, 
#       reps=2, # step 4
#       B=10, 
#       alpha= 0.05,
#       C=6,
#       varcovar_matrix = varcovar_matrix)
#   case_end <- Sys.time()
#           case_runtime <- as.numeric(difftime(case_end, case_start, units = "mins"))
#           cat("Finished at:", format(case_end, "%I:%M %p"), "\n")
#           cat("Runtime for this case:", round(case_runtime, 2), "minutes\n")
#   
#   # print(colMeans(out))
#   filename <- paste0(
#     paste(paste0("K",gsub("\\.", "p", as.character(K))),
#           paste0("sd",gsub("\\.", "p", as.character(sd))),
#           paste0("r",gsub("\\.", "p", as.character(r))),
#           sep = "_"),
#     ".rds")
#   
#   # saveRDS(out, file = filename)
# }
# }
# 
# # stopCluster(cl)
# #1.964865
# 
# # 1.964873 mali
```



```{r}
source("R/compute_metrics.R")
library(doParallel)
cl=parallel::makeCluster(15)
registerDoParallel(cl)
case_start <- Sys.time()


df <- readRDS("data/mean_travel_time_ranking_2011.rds")
mean <- 23.8
sds <- c(6.0)
Ks <- c(50, 40, 30, 20, 10)
# corr <- c(0.1, 0.5, 0.9)

for (sd in sds) {
  for (K in Ks) {
  print(cat("RESULTS FOR SD =",sd, "; K =", K))
  corr_matrix <-block_corr(block_sizes=c(.2*K,.3*K, .5*K), rho_within=c(0.9, 0.5, 0.1), rho_between=0.0)# block_corr(block_sizes=c(0.3*K,0.7*K), rho_within=c(0.9, 0.1), rho_between=0.0) #  block_corr(block_sizes=c(5,5), rho_within=c(0.75, 0.15), rho_between=0.0) #block_corr(block_sizes=c(5,5), rho_within=c(0.85, 0.25), rho_between=0.0)# (1 - r) * diag(K) + r * matrix(1, K, K)

  set.seed(123974)
  true_theta <- rnorm(K, mean, sd)
  true_sds <- df$S[1:K]
  variance_vector <- true_sds^2
  delta <- diag(variance_vector)
  varcovar_matrix <- delta^(1/2) %*% corr_matrix %*% delta^(1/2)
  out <- implement_algorithm2(
      true_theta = true_theta,
      K = K, 
      reps=5000, # step 4
      B=500,#700, 
      alpha= 0.05,
      C=300,#350,
      varcovar_matrix = varcovar_matrix)
  case <- paste(paste0("K",gsub("\\.", "p", as.character(K))),
          paste0("sd",gsub("\\.", "p", as.character(sd))),
          paste0("r",gsub("\\.", "p", "unbalanced-block")), #as.character(r))),
          sep = "_")
  case_end <- Sys.time()
          case_runtime <- as.numeric(difftime(case_end, case_start, units = "mins"))
          cat("Finished at:", format(case_end, "%I:%M %p"), "\n")
          cat("Runtime for", case, round(case_runtime, 2), "minutes\n")
  
  print(colMeans(out))
  filename <- paste0(
    case,
    ".rds")
  
  saveRDS(out, file = filename)
}
}
stopCluster(cl)
```


```{r}
diag(K) + r * matrix(1, K, K)
```












```{r}
colMeans(readRDS("K10_sd3p6_r0p1.rds"))
```


```{r}
filename
```








```{r}
colMeans(out) # K10_r0p5_sd3p6

# # Finished at: 12:59 AM 
# Finished at: 12:57 PM 
# Runtime for this case: 189.97 minutes
```

```{r}
r <- 0.9
sd <- 2.00 
K <- 10


```


```{r}
colMeans(out) # K10_r0p1_sd3p6

# # Finished at: 12:59 AM 
# Finished at: 12:57 PM 
# Runtime for this case: 189.97 minutes

```

```{r}
colMeans(out)
```


```{r}
# Runtime for this case: 189.65 minutes K10_r0p9_sd2p0
# Runtime for this case: 195.53 minutes K10_r0p5_sd2p0
# Runtime for this case: 189.8 minutes K10_r0p1_sd2p0

colMeans(out) # K10_r0p9_sd2p0
```

```{r}
colMeans(out) # K10_r0p5_sd2p0
# Finished at: 12:59 AM 
```




```{r}
# Source - https://stackoverflow.com/a/63126233
# Posted by heds1
# Retrieved 2026-01-05, License - CC BY-SA 4.0

base_dir <- './balanced_two/'
all_files <- paste0(base_dir, 
                    list.files(base_dir, pattern = "\\.rds$", 
                               recursive = FALSE))

summarize_means <- function(file){
  dat <- readRDS(file)
  summary <- colMeans(dat)
  return(summary)
  #summary['file'] = file
  #return(t(as.data.frame(summary)))
}

df <- as.data.frame(do.call("rbind", lapply(all_files, summarize_means)))
df$file <-all_files
df$file
```


```{r}
library(tidyr)
library(dplyr)
# df %>% separate(file, sep = "_", into = c("K", "sd", 'r')) #%>% mutate(sd = sd.replace)
```

```{r}
file
```


```{r}
df$file <- sub("balanced_two/", "", df$file)
df
```


```{r}
summ <- df %>% separate(file, sep = "_", into = c("K", "sd", 'r'))
# sub("sd", "", summ$sd)

```



```{r}
# Source - https://stackoverflow.com/a/55986799
# Posted by G. Grothendieck, modified by community. See post 'Timeline' for change history
# Retrieved 2026-01-05, License - CC BY-SA 4.0
summ <- df %>% separate(file, sep = "_", into = c("K", "sd", 'r'))

summ$sd <- sub("sd", "", summ$sd) 
summ$sd <- sub("p", ".", summ$sd) 
summ$K <- sub("./K", "", summ$K) 
summ$r <- sub("r", "", summ$r) 
summ$r <- sub(".rds", "", summ$r) 
summ$r <- sub("p", ".", summ$r) 
summary <- summ %>%  mutate(sd = as.numeric(sd)) %>%  
  # mutate(r = as.numeric(r)) %>%  
  mutate(r = r) %>%  
  mutate(K = as.numeric(K))

summary

# 
summary_form <- summary %>% pivot_longer(
    cols = `t1_nonrankbased`:`coverage_bonferroni`,
    names_to = "metric",
    values_to = "value"
) %>%
  separate(metric, into=c("metric", "approach"), extra = "merge", sep = "_") %>%
  pivot_wider(names_from = "approach", values_from = "value")

summary_form
write.csv(summary_form, "summary_2balanced.csv")
```

