---
title: "Nonrankbased"
author: "Shaine"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    number_sections: true
    toc: true
    toc_float:
      collapsed: false
      toc_depth: 5
    fig_caption: true
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.align = "center", fig.width = 5, fig.height = 3, comment="", warning = FALSE, message = FALSE)
```

# Dataset

The following could be used as simulation settings for the thetas

Generate mean values from N(23.8, sd), where sd = 3.6, sd = 6, sd = 2

K = 5, 10, 30, 51

```{r}
library(dplyr)
library(kableExtra)
library(doParallel)
library(foreach)
library(tictoc)


sd <- 3.6 #  sd = 3.6, sd = 6, sd = 2
mean <- 23.8

set.seed(123974)
theta <- rnorm(51, mean, sd)
df <- readRDS("../../data/mean_travel_time_ranking_2011.rds")
df$theta_k <- theta
full_dataset <- df %>% dplyr::select(theta_k, k,S)
kable(full_dataset) %>% kable_styling(bootstrap_options = "responsive")
```

SE can be the same one used in the study of Klein 

```{r results='asis'}
alpha <- 0.1
K <- 51
B<- 1000
dataset <- full_dataset[order(full_dataset$k),][1:K,]
```

# Algorithm 1

$$
\boldsymbol{\Sigma} =  \boldsymbol{\Delta}^{\frac{1}{2}} \boldsymbol{\rho} \boldsymbol{\Delta}^{\frac{1}{2}}
\\
\boldsymbol{\Delta} = \text{diag}\{\sigma^2_1, \sigma^2_2, \dots, \sigma^2_K\}
\\
\boldsymbol{\rho} = \text{population correlation matrix}
$$



```{r}
# library("expm")
# m <- 100*diag(5) 
# sqrtm(delta) == delta2^(1/2)
```

```{r}
corr <- 0.9

# Sigma = (diag(sds[1:K])%*%corr)%*%diag(sds[1:K])

corr_matrix <- (1 - corr) * diag(K) + corr * matrix(1, K, K)
#variance_vector <- dataset$S^2
sd_vector <- dataset$S
delta <- diag(sd_vector)

# varcovar_matrix = Sir Mike's Sigma
# varcovar_matrix <- delta^(1/2) %*% corr_matrix %*% delta^(1/2)
varcovar_matrix <- delta %*% corr_matrix %*% delta
```



```{r results='asis'}
source("../../R/algo1_nonrankbased.R")

corr <- 0.1
corr_matrix <- (1 - corr) * diag(K) + corr * matrix(1, K, K)
variance_vector <- dataset$S^2
delta <- diag(variance_vector)

varcovar_matrix <- delta^(1/2) %*% corr_matrix %*% delta^(1/2)

res <- run_algorithm1(B, dataset$theta_k,alpha = 0.1, varcovar_matrix=varcovar_matrix)
#kable(res) %>% kable_styling(bootstrap_options = "responsive")
```

# Algorithm 2:

```{r eval = FALSE}
source("../../R/algo1_nonrankbased.R")
library("doRNG")
get_coverage <- function(true_theta,
                         K, 
                         reps = 5, # step 4
                         B=100, 
                         alpha= 0.10,
                         varcovar_matrix){
  foreach(iter = 1:reps, 
          .combine = rbind,
          .packages = c("foreach", "arrow", "dplyr", "MASS"),
          .export = c("run_algorithm1","get_ranks", 
                      "get_t2")
          ) %dorng% {
  
  # step 1 =====================================================================
  

  theta_hat <- mvrnorm(n = 1, 
                       mu = true_theta, 
                       Sigma = varcovar_matrix)
  print(length(theta_hat))
  
  

  # step 2 =====================================================================
  result <- run_algorithm1(B,
                           theta_hat,# true_sds,# iter, 
                           alpha, 
                           varcovar_matrix)
  
  # print(cbind(true_theta = true_theta[1:5],
  #             theta_hat  = theta_hat[1:5]))
  
  # step 3 =====================================================================
  inside_check_nonrank <- all(result$ci_lower<=true_theta) & all(true_theta<=result$ci_upper)
  
  gamma = 1-(1-alpha)^(1/K)
  z1 = qnorm(1-gamma/2)
  result$ind_ci_lower <- theta_hat - z1*sqrt(diag(varcovar_matrix))
  result$ind_ci_upper <- theta_hat + z1*sqrt(diag(varcovar_matrix))
  inside_check_ind <- all(result$ind_ci_lower<=true_theta) & all(true_theta<=result$ind_ci_upper)
  
  z2 = qnorm(1-(alpha/2)/2)
  result$bonf_ci_lower <- theta_hat - z2*sqrt(diag(varcovar_matrix))
  result$bonf_ci_upper <- theta_hat + z2*sqrt(diag(varcovar_matrix))
  inside_check_bonf <- all(result$bonf_ci_lower<=true_theta) & all(true_theta<=result$bonf_ci_upper)
  
  tuple_list <- t(apply(
    data.frame(ci_lower = result$ci_lower,
               ci_upper = result$ci_upper), 1, function(row) as.numeric(row)))
  ind_rank_range_length <- sapply(1:K, function(x) length(get_ranks(x, tuple_list)$ranks))
  t2_val_nonrank <- get_t2(ind_rank_range_length)
  
  tuple_list <- t(apply(
    data.frame(ind_ci_lower = result$ind_ci_lower,
               ind_ci_upper = result$ind_ci_upper), 1, function(row) as.numeric(row)))
  ind_rank_range_length <- sapply(1:K, function(x) length(get_ranks(x, tuple_list)$ranks))
  t2_val_ind <- get_t2(ind_rank_range_length)
  
  tuple_list <- t(apply(
    data.frame(ci_lower = result$bonf_ci_lower,
               ci_upper = result$bonf_ci_upper), 1, function(row) as.numeric(row)))
  ind_rank_range_length <- sapply(1:K, function(x) length(get_ranks(x, tuple_list)$ranks))
  t2_val_bonf <- get_t2(ind_rank_range_length)
  
  #write_feather(result, sprintf("../output/iters/test/K%d/sorted_ci_%04d.feather", K, iter))

  
  data.frame(t2_nonrank = t2_val_nonrank,
             inside_check_nonrank = inside_check_nonrank,
             t2_bonf = t2_val_bonf,
             inside_check_bonf = inside_check_bonf,
             t2_ind = t2_val_ind,
             inside_check_ind = inside_check_ind)

}
}

```





```{r eval = FALSE}
#sd <- 3.6 #  sd = 3.6, sd = 6, sd = 2
mean <- 23.8

df <- readRDS("../../data/mean_travel_time_ranking_2011.rds")

cl=parallel::makeCluster(15)
registerDoParallel(cl)

# sds <- c(2, 3.6, 6)
sds <- c(2, 3.6, 6)
Ks <- c(51, 40, 30, 20, 10, 5)
corrs <- c(0.1,0.5,0.9)
alphas <- c(0.1)#c(0.05, 0.1, 0.15, 0.2)

for (sd in sds) {
  for (K in Ks) {
    set.seed(123974)
    true_theta <- rnorm(K, mean, sd)
    true_sds <- df$S[1:K]
    
    for (corr in corrs) {
          for (alpha in alphas) {
            corr_matrix <- (1 - corr) * diag(K) + corr * matrix(1, K, K)
            variance_vector <- true_sds^2 #dataset$S^2
            delta <- diag(variance_vector)
            varcovar_matrix <- delta^(1/2) %*% corr_matrix %*% delta^(1/2)

            
            tic("Running...")
            coverage_output_df <- get_coverage(true_theta,
                                               K, 
                                               reps = 5000, 
                                               B = 500, 
                                               alpha=alpha,
                                               varcovar_matrix = varcovar_matrix)
            toc()
          
            saveRDS(coverage_output_df,  paste0("output/coverage_probability_",K,"_", sd, "_", corr, "_", alpha, ".rds"))
            coverage_output_df

    }
    }
  }
}

stopCluster(cl)
```



```{r results='asis'}
# sds <- c(2,6)#, 3.6, 6)
# Ks <- c(51)#1, 40, 30, 20, 10, 5)

# sds <- c(2, 3.6, 6)
# Ks <- c(5,10,30,51)
# corrs <- c(0.1,0.5,0.9)
# alphas <- c(0.05, 0.1, 0.15, 0.2, 0.3, 0.4, 0.5)

sds <- c(2, 3.6, 6)
Ks <- c(51, 40, 30, 20, 10, 5)
corrs <- c(0.1,0.5,0.9)
alphas <- c(0.1)#c(0.05, 0.1, 0.15, 0.2)


param_grid <- expand.grid(K = Ks, sd = sds, corr = corrs, alpha = alphas)

results <- do.call(rbind, lapply(seq_len(nrow(param_grid)), function(i) {
  K <- param_grid$K[i]
  sd <- param_grid$sd[i]
  corr <- param_grid$corr[i]
  alpha <- param_grid$alpha[i]
  
  a <- readRDS(paste0("output/coverage_probability_", K, "_", sd, "_", corr, "_", alpha, ".rds"))
  
  data.frame(
    K = K,
    sd = sd,
    corr = corr,
    alpha = alpha,
    Cov_nonrank = mean(a$inside_check_nonrank),# == K),
    T_nonrank = mean(a$t2_nonrank),
    Cov_ind = mean(a$inside_check_ind),# == K),
    T_ind = mean(a$t2_ind),
    Cov_bonf = mean(a$inside_check_bonf),# == K)
    T_bonf = mean(a$t2_bonf)
  )
}))


library(DT)

#results
datatable(results %>% arrange(-sd) %>% dplyr::select(
    K, sd, corr, alpha,
    Cov_nonrank, Cov_ind, Cov_bonf,
    T_nonrank, T_ind, T_bonf) %>% mutate(across(where(is.numeric), ~ round(.x, 4))) ,
           extensions = c("Buttons" , "FixedColumns"),
           filter = 'top',
           options = list( autoWidth = TRUE ,
                           dom = 'Blftip',
                           pageLength = 100,
                           searchHighlight = FALSE,
                           buttons = c('copy', 'csv', 'print'),
                           scrollX = TRUE,
                           fixedColumns = list(leftColumns = 2)),
           class = c('compact cell-border stripe hover') ,
           rownames = FALSE)
```



```{r echo = FALSE}
  # #inside_check_nonrank <- sum((true_theta >= result$ci_lower) & (true_theta <= result$ci_upper))
  # 
  # inside_check_nonrank <- all(result$ci_lower<=true_theta) & all(true_theta<=result$ci_upper)
  # 
  # 

  # 
  # # inside_check_ind <- sum((true_theta >= result$ind_ci_lower) &
  # #                       (true_theta <= result$ind_ci_upper))
  # 

  # 
  # 

  # inside_check_bonf <- sum((true_theta >= result$bonf_ci_lower) &
  #                       (true_theta <= result$bonf_ci_upper))

  # 
  # 
  # data.frame(#t2_nonrank = t2_val_nonrank,
  #            inside_check_nonrank = inside_check_nonrank,
  #            #t2_bonf = t2_val_bonf,
  #            inside_check_bonf = inside_check_bonf,
  #            #t2_ind = t2_val_ind,
  #            inside_check_ind = inside_check_ind)
```

