```{r}
source("/home/realiseshewon/PDev/kde-ranking/R/create_plot.R")
dataset<-readRDS("/home/realiseshewon/PDev/kde-ranking/data/true_theta.rds")
```

Figure \@ref(fig:true-theta-boxplot) shows how the spread of the $\theta$ varies in the cases considered in Table \@ref(tab:true-theta-table)

```{r tab.cap="True $\\theta$ values used in the simulation have different levels of variability.", include = FALSE}

source("/home/realiseshewon/PDev/kde-ranking/R/create_table.R")
create_table_for_true_theta(
dataset %>% 
  select(K, data_spread, true_theta) %>%
  group_by(K, data_spread) %>%
  summarise(true_theta = paste(round(true_theta, 1), collapse = ", "), .groups = "drop") %>%
  mutate(R = "$\\mathbf{R}_{eq, \\rho} = 0.1, 0.5, 0.9$ $\\mathbf{R}_{block} - 2, 3$ blocks")
)
```



```{r true-theta-boxplot, fig.cap="True $\\theta$ values used in the simulation have different levels of variability.", message = FALSE, warning=FALSE, fig.pos='H'}
source("/home/realiseshewon/PDev/kde-ranking/R/create_plot.R")

dataset<-readRDS("/home/realiseshewon/PDev/kde-ranking/data/true_theta.rds")
create_boxplot_for_true_theta(dataset)
```


```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
source("/home/realiseshewon/PDev/kde-ranking/R/preprocess_data.R")
source("/home/realiseshewon/PDev/kde-ranking/R/create_table.R")


# equicorr <- TRUE
# eq_res <- combine_summaries(
#   "/home/realiseshewon/PDev/kde-ranking/simulation_results/summaries/summary_k",
#   TRUE
# ) %>%  mutate(across(5:9, round, 3))
# 
# 
# bl_res <- combine_summaries(
#   "/home/realiseshewon/PDev/kde-ranking/simulation_results/summaries/summary_block",
#   FALSE
# ) %>%  mutate(across(5:9, round, 3))


eq_res <- combine_summaries(
  "/home/realiseshewon/PDev/kde-ranking/simulation_results/summaries/summary_k",
  TRUE
) %>% mutate(Variance = factor(ifelse(sd == 2, 'Low', 
                                      ifelse(sd == 3.6, "Moderate", "High")),
                               levels = c("Low", "Moderate", "High"), 
                               ordered = TRUE)) %>% 
  mutate(`Correlation structure` = "Equicorrelated")  %>%
  mutate(across(c(nonrankbased,rankbased_asymptotic, rankbased_level2bs, independent, bonferroni), round, 3)) 
  #mutate(across(5:8, round, 3))


bl_res <- combine_summaries(
  "/home/realiseshewon/PDev/kde-ranking/simulation_results/summaries/summary_block",
  FALSE
) %>% 
mutate(
  Variance = factor(ifelse(sd == 2, 'Low', 
                    ifelse(sd == 3.6, "Moderate", "High")),
                    levels = c("Low", "Moderate", "High"), 
                    ordered = TRUE),
  
  r = factor(
    case_when(
      r == "balanced-block" & blocks == 2 ~ "B2",
      r == "unbalanced-block" & blocks == 2 ~ "U2",
      r == "unbalanced-block" & blocks == 3 ~ "UL3",
      r == "unbalanced-block-high" & blocks == 3 ~ "UH3",
      TRUE ~ r
    ),
    levels = c("B2", "U2", "UL3", "UH3"),
    ordered = TRUE
  )
) %>% 
    mutate(`Correlation structure` = "Block Diagonal") %>%
  mutate(across(c(nonrankbased,rankbased_asymptotic, rankbased_level2bs, independent, bonferroni), round, 3)) 
```


\blandscape



```{r}
# bl_res %>% filter(metric != "coverage") %>% #select(-c(rankbased_asymptotic,rankbased_level2bs)) %>%
#   mutate(r = paste(r, blocks, sep = '-')) %>%
#   mutate(r = case_when(
#     r == "balanced-block-2" ~ "B2",
#     r == "unbalanced-block-2" ~ "U2",
#     r == "unbalanced-block-3" ~ "UL3",
#     r == "unbalanced-block-high-3" ~ "UH3",
#     TRUE ~ r
#   ))%>% 
#   mutate(Variability =ifelse(sd==2.0, "low", ifelse(sd==3.6, "med", "high"))) %>% 
#   filter(metric == 't1') %>%
#   select(-c(sd, blocks, metric))%>%
#   pivot_wider(names_from = Variability,
#               values_from = c(independent,bonferroni,nonrankbased,rankbased_asymptotic,rankbased_level2bs),
#               names_sep = "-") %>% 
#   arrange(K, r)
```

```{r}
# bl_test<- bl_res %>% filter(metric != "coverage") %>% #select(-c(rankbased_asymptotic,rankbased_level2bs)) %>%
#   mutate(r = paste(r, blocks, sep = '-')) %>%
#   mutate(r = case_when(
#     r == "balanced-block-2" ~ "B2",
#     r == "unbalanced-block-2" ~ "U2",
#     r == "unbalanced-block-3" ~ "UL3",
#     r == "unbalanced-block-high-3" ~ "UH3",
#     TRUE ~ r
#   ))%>% 
#   mutate(Variability =ifelse(sd==2.0, "low", ifelse(sd==3.6, "med", "high"))) %>% 
#   filter(metric == 't1') %>%
#   select(-c(sd, blocks, metric))%>%
#   pivot_wider(names_from = Variability,
#               values_from = c(independent,bonferroni,nonrankbased,rankbased_asymptotic,rankbased_level2bs),
#               names_sep = "-") %>% 
#   arrange(K, r) %>%
#   select(r,
#     `independent-low`, `bonferroni-low`, `nonrankbased-low`,
#     `independent-med`, `bonferroni-med`, `nonrankbased-med`,
#     `independent-high`, `bonferroni-high`, `nonrankbased-high`)
# 
# tabb1 <- preprocess_tightness_measure(eq_res, "t1", equicorr)
# # 
# # if (!equicorr) {
# #   tabb1 <- tabb1 %>% select(-c(r, blocks))
# # }
# 
# tabb1 <- tabb1 %>% select(K, r,
#     independent_low, bonferroni_low, nonrankbased_low,
#     independent_med, bonferroni_med, nonrankbased_med,
#     independent_high, bonferroni_high, nonrankbased_high)
# 
# eq_padded_ordered <- tabb1 %>%
#   group_by(K) %>% # or whatever variable defines your 10, 20, 30 groups
#   group_modify(~ add_row(.x)) %>% 
#   ungroup()
# 
# cbind(eq_padded_ordered, bl_test)
```




```{r nonrank-eq-t1}
options(knitr.kable.NA = "")

create_table_for_tightness_measure(prepare_appendix_t_measure_table(eq_res, bl_res, unordered=TRUE, tmeasure = "t1"), 
                                   "t1", unordered = TRUE)

```
```{r nonrank-eq-t2}
options(knitr.kable.NA = "")

create_table_for_tightness_measure(prepare_appendix_t_measure_table(eq_res, bl_res, unordered=TRUE, tmeasure = "t2"), 
                                   "t2", unordered = TRUE)

```


```{r nonrank-eq-t3}
options(knitr.kable.NA = "")
create_table_for_tightness_measure(prepare_appendix_t_measure_table(eq_res, bl_res, unordered=TRUE, tmeasure = "t3"), 
                                   "t3", unordered = TRUE)

```





```{r rank-eq-t1}
options(knitr.kable.NA = "")

create_table_for_tightness_measure(prepare_appendix_t_measure_table(eq_res, bl_res, unordered=FALSE, tmeasure = "t1"), 
                                   "t1", unordered = FALSE)

```
```{r rank-eq-t2}
options(knitr.kable.NA = "")

create_table_for_tightness_measure(prepare_appendix_t_measure_table(eq_res, bl_res, unordered=FALSE, tmeasure = "t2"), 
                                   "t2", unordered = FALSE)

```


```{r rank-eq-t3}
options(knitr.kable.NA = "")
create_table_for_tightness_measure(prepare_appendix_t_measure_table(eq_res, bl_res, unordered=FALSE, tmeasure = "t3"), 
                                   "t3", unordered = FALSE)

```

\elandscape
