## Joint Confidence Regions for Pulse Asia Results


```{r}
source("/home/realiseshewon/PDev/kde-ranking/R/generate_true_theta.R")
source("/home/realiseshewon/PDev/kde-ranking/R/simulate/compute_ci.R")
source("/home/realiseshewon/PDev/kde-ranking/R/simulate/compute_metrics.R")
source("/home/realiseshewon/PDev/kde-ranking/R/calculate_ci_application.R")
source("/home/realiseshewon/PDev/kde-ranking/R/preprocess_data.R")
source("/home/realiseshewon/PDev/kde-ranking/R/create_plot.R")
source("/home/realiseshewon/PDev/kde-ranking/R/create_table.R")
  
cand <- generate_true_theta_rd(persist_df = FALSE)

cand$Makabayan <- ifelse(cand$Party == 'MKBYN', 1, 0)

#corr_matrix <-block_corr(block_sizes=c(2, 12, 10, 2, 7, 18), rho_within=c(0.9, 0.9, 0.9, 0.9, 0.9, 0.1), rho_between=0.0)
corr_matrix <-block_corr(block_sizes=c(2, 12, 10, 2, 11, 27), rho_within=c(0.9, 0.9, 0.9, 0.9, 0.9, 0.1), rho_between=0.0)

dataset_all <- cand %>%
  mutate(Voting_for_dec = `Voting For`/100) %>%
  #filter(Voting_for_dec >= 0.01) %>%
  mutate(se = sqrt((Voting_for_dec*(1-Voting_for_dec))/1200) ) %>%
  select(-Voting_for_dec) %>% 
  arrange(desc(`Voting For`)) %>%  
  arrange(desc(DuterTen), desc(Alyansa),desc(KiBam), desc(Makabayan))  %>%
  rename(`Rank UB_pulse` = `Rank UB`, `Rank LB_pulse` = `Rank LB`)

ci_results <- get_ci_for_app_data(
  theta_hat = (dataset_all$`Voting For`)/100,
  true_sds = dataset_all$se,
  K = dim(dataset_all)[1],
  alpha = 0.05,
  B <- 500,
  corr_matrix=corr_matrix 
  )

```

```{r}
create_basic_results_table(get_tmeasures_for_app_data(ci_results),
                           "Joint Confidence Region Tightness Measures: r = 0.9")
```



```{r pulse-result,fig.height=5, fig.cap = "95% Joint Confidence Region for Candidates with at least 1% Votes"}
prepared_data <- prepare_plotting_data_for_pulse(ci_results,dataset_all)
create_plot_for_app_data(prepared_data, Candidate, k, reverse=TRUE,
                                  color_map = c("DuterTen" = "limegreen", "Alyansa" = "red", "KiBam" = "gold", "Makabayan" = "blue","DuterTen-Alyansa" = "black"))
```

Figure \@ref(fig:pulse-result) assumes high correlations within blocks of alliances and political slates.

## Joint Confidence Regions for Mean Travel Time to Work


```{r}
dataset_all <- readRDS("/home/realiseshewon/PDev/kde-ranking/data/mean_travel_time_ranking_2011.rds")

dataset_all$density <- c(94.4, 1.2, 56.3,
                      56.0, 239.1, 48.5,
                      738.1, 460.8, 9856.5,
                      350.6,168.4,211.8,
                      19.0,	231.1,181.0,
                      54.5,34.9,109.9,
                      104.9,43.1,594.8,
                      839.4,174.8,66.6,
                      63.2,87.1, 6.8,
                      23.8, 24.6, 147.0, 
                      1195.5,17.0, 411.2,
                      196.1, 9.7, 282.3, 
                      54.7, 39.9, 283.9,
                      1018.1,153.9,10.7,
                      153.9,96.3,	33.6,
                      67.9, 202.6, 101.2,
                      77.1, 105.0, 5.8)


dataset_all <- dataset_all %>% mutate(
  density_group = ifelse(density > 0 & density <= 20, 1, 
                         ifelse(density > 20 & density <= 50, 2, 
                                ifelse(density > 50 & density <= 100, 3,
                                       ifelse(density > 100 & density <= 200, 4, 5))))
) %>% arrange(desc(theta_k)) %>% arrange(desc(density_group))

# attempt2 <- dataset_all #%>% arrange(desc(theta_k)) #%>% head(30)# 
# 
# 
# #attempt2 %>% group_by(density_group) %>% count()
# attempt2
# dataset_all
```



```{r}

corr_matrix <-block_corr(block_sizes=c(15, 11, 11, 7, 7), rho_within=c(0.9, 0.9, 0.9, 0.9, 0.9), rho_between=0.0)

# dataset_all <- cand %>%
#   mutate(Voting_for_dec = `Voting For`/100) %>%
#   #filter(Voting_for_dec >= 0.01) %>%
#   mutate(se = sqrt((Voting_for_dec*(1-Voting_for_dec))/1200) ) %>%
#   select(-Voting_for_dec) %>% 
#   arrange(desc(`Voting For`)) %>%  
#   arrange(desc(DuterTen), desc(Alyansa),desc(KiBam), desc(Makabayan))  %>%
#   rename(`Rank UB_pulse` = `Rank UB`, `Rank LB_pulse` = `Rank LB`)

ci_results <- get_ci_for_app_data(
  theta_hat = dataset_all$theta_k,
  true_sds = dataset_all$S,
  K = dim(dataset_all)[1],
  alpha = 0.05,
  B <- 500,
  corr_matrix=corr_matrix 
  )
```


```{r}
create_basic_results_table(get_tmeasures_for_app_data(ci_results),
                           "Joint Confidence Region Tightness Measures: r = 0.9")
```





```{r}
# corr_matrix <-block_corr(block_sizes=c(15, 11, 11, 7, 7), rho_within=c(0.9, 0.9, 0.9, 0.9, 0.9), rho_between=0.0)
# #corr_matrix <-block_corr(block_sizes=c(3,5,9,13), rho_within=c(0.9, 0.9,0.9, 0.9), rho_between=0.0)
# 
# set.seed(123974)
# theta_hat <- attempt2$theta_k
# true_sds <- attempt2$S
# K <- dim(attempt2)[1]
# 
# variance_vector <- true_sds^2
# delta <- diag(variance_vector)
# varcovar_matrix <- delta^(1/2) %*% corr_matrix %*% delta^(1/2)
# B <- 500
# 
# alpha <- 0.05
# S <- sqrt(diag(varcovar_matrix))
# 
#     
# ci_methods <- list(
#   nonrankbased = function() get_ci_nonrankbased(B = B,
#                                                 theta_hat = theta_hat,
#                                                 alpha = alpha,
#                                                 varcovar_matrix = varcovar_matrix),
#   # rankbased_asymptotic = function() get_ci_rankbased_asymptotic(B = B,
#   #                                                               theta_hat = theta_hat,
#   #                                                               varcovar_matrix = varcovar_matrix,
#   #                                                               alpha = alpha),
#   # rankbased_level2bs = function() get_ci_rankbased_level2bs(B = B,
#   #                                                           C = 300,
#   #                                                           theta_hat = theta_hat,
#   #                                                           varcovar_matrix = varcovar_matrix,
#   #                                                           alpha = alpha),
#   independent  = function() get_ci_independent(theta_hat = theta_hat, S = S, alpha = alpha),
#   bonferroni   = function() get_ci_bonferroni(theta_hat = theta_hat, S = S, alpha = alpha)
# )
# ci_results <- lapply(ci_methods, function(f) f())
# 
# dataset_all <- attempt2
# 
# dataset_all$`Rank LB_nonrank` <- sapply(process_ci_result(result = ci_results$nonrankbased, K=K), min)
# dataset_all$`Rank UB_nonrank` <- sapply(process_ci_result(result = ci_results$nonrankbased, K=K), max)
# 
# dataset_all$`Rank LB_independent` <- sapply(process_ci_result(result = ci_results$independent, K=K), min)
# dataset_all$`Rank UB_independent` <- sapply(process_ci_result(result = ci_results$independent, K=K), max)
# 
# dataset_all$`Rank LB_bonferroni` <- sapply(process_ci_result(result = ci_results$bonferroni, K=K), min)
# dataset_all$`Rank UB_bonferroni` <- sapply(process_ci_result(result = ci_results$bonferroni, K=K), max)
# 
# #dataset_all <- dataset_all# %>% arrange(desc(`Voting For`))
# 
# # df <- readRDS("../data/mean_travel_time_ranking_2011.rds")
# dataset_all$k <- seq(1,K, 1)
# dataset_all$sample_rank <- seq(1,K, 1)
# dataset_all$order_index <- seq(1,K, 1)
# 
# dataset_all <- dataset_all %>% pivot_longer(
#     cols = starts_with("Rank"), # Selects columns that start with "Test"
#     names_to = "type",   # Name for the new column storing original column names
#     values_to = "Ranks"        # Name for the new column storing the values
#   )%>%
#   separate(
#     col = type,  # The column to separate
#     into = c("Rank", "Approach"), # Names for the new columns
#     sep = "_",           # The delimiter is an underscore
#     extra = "merge"      # Merges any extra parts into the last column ("rest_of_string")
#   ) %>% pivot_wider(
#     names_from = Rank,
#     values_from = Ranks
#   )
# 
# dataset_all
```




```{r}
prepared_data <- prepare_plotting_data_for_traveltime(ci_results,dataset_all)
```



```{r traveltime-result,fig.height=5, fig.cap = "95% Joint Confidence Region for Mean Travel Times in the US"}
create_plot_for_app_data(prepared_data, iso, theta_k, reverse=FALSE,
                                  color_map = c("1" = "limegreen", "2" = "red", "3" = "gold", "4" = "blue","5" = "violet"))
```





```{r}
# prepared_data <- prepare_plotting_data_for_traveltime(ci_results,dataset_all)#dat_to_plot %>% filter(Approach != 'pulse') #%>% filter(Approach != 'independent')
# data_to_plot$Approach <- factor(data_to_plot$Approach, levels = c('independent', 'bonferroni', 'nonrank'))
# 
# cap_first <- function(x) {
#   paste0(toupper(substring(x, 1, 1)), substring(x, 2))
# }
# 
# 
# p <- ggplot(data = data_to_plot, aes(x = reorder(iso, theta_k),
#                                      y = as.numeric(string_ranks))) + 
#   geom_point(data = subset(data_to_plot, highlight0 == "yes"), shape = 16, size = 1, color = "black") +
#   geom_point(data = subset(data_to_plot, highlight0 == "no"), shape = 4, size = 0.25, aes(color = highlight1)) + 
#   scale_color_manual(values = c("1" = "limegreen", "2" = "red", "3" = "gold", "4" = "blue","5" = "violet"))+
#   scale_y_continuous(breaks = seq(1, max(prepared_data$k), by = 4)) +
#   labs(title='95% Joint Confidence Region for Candidates with at least 1% Votes') + xlab('Candidate') + ylab('Sample rank') +
#   theme_bw() +
#   theme(axis.text.x = element_text(hjust = 1, size = 5),
#         axis.text.y = element_text(size=5)
#   ) +
#   guides(colour="none") +
#   theme(axis.line = element_line(colour = "gray"),
#         panel.grid.minor = element_blank(),
#         panel.grid.major.x = element_blank(),
#         text = element_text(family = "serif")) +
#   facet_wrap(~Approach, ncol=length(unique(data_to_plot$Approach)), 
#              labeller = as_labeller(cap_first)) + coord_flip()
# 
# p
```





```{r}
# pd <- position_dodge(width = 0.8) 
# 
# 
# dat_to_plot <- dat_to_plot %>% filter(Approach %in% c('bonferroni', 'nonrank'))
# p <- ggplot(data = dat_to_plot, aes(x = reorder(iso, theta_k),
#                                y = as.numeric(string_ranks))) + 
#   geom_point(data = subset(dat_to_plot, highlight0 == "yes"), shape = 16, size = 1, color = "black", position = pd) +
#   geom_point(data = subset(dat_to_plot, highlight0 == "no"), shape = 4, size = 0.25, position = pd) +#, aes(color = highlight1)) + 
#   #scale_color_manual(values = c("1" = "limegreen", "2" = "red", "3" = "gold", "4" = "blue","5" = "violet"))+
#   scale_y_continuous(breaks = seq(1, K, by = 4)) +
#   labs(title='Visualization of the 95% joint confidence') + xlab('theta_k') + ylab('Sample rank') +
#   theme_bw() +
#   theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6),
#         axis.text.y = element_text(size=6)
#         ) +
#  # guides(colour="none") +
#   theme(axis.line = element_line(colour = "gray"),
#     panel.grid.minor = element_blank(),
#     panel.grid.major.x = element_blank(),
#     text = element_text(family = "serif")) +
#   facet_wrap(~Approach, ncol=2) #+ coord_flip()
# 
# p
```




